### ISSUE TITLE
Missing BlendVOCA/templates.pkl file when running main.py

### ISSUE THREAD

**Issue by damithsenanayake** [SaltedSlark/Fast-3D-Talking-Face#3]
Hi All, 
I've been running into a few issues when running main.py
First, I had to download the wave2vec library separately, which wasn't mentioned in the documentation (would be good to add). 

Now I'm running into the issue where it's looling for a pickle file 'BlendVOCA/templates.pkl', and won't proceed from there. 

stacktrace: 
```python
Traceback (most recent call last):
  File "/home/damith/Fast-3D-Talking-Face/main.py", line 139, in <module>
    main()
  File "/home/damith/Fast-3D-Talking-Face/main.py", line 129, in main
    dataset = get_dataloaders(args)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/damith/Fast-3D-Talking-Face/data_loader.py", line 94, in get_dataloaders
    train_data, valid_data, test_data, subjects_dict = read_data(args)
                                                       ^^^^^^^^^^^^^^^
  File "/home/damith/Fast-3D-Talking-Face/data_loader.py", line 47, in read_data
    with open(template_file, 'rb') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'BlendVOCA/templates.pkl'
```

**Comment by SaltedSlark** [comment]
Sorry, In fact this file is useless, I have revise the code, please update and try again.
